#! /bin/bash

# include some files
OSTMU_FOLDER="/opt/ostmu"
source "${OSTMU_FOLDER}/etc/config"

# define some vars
USER_NAME=$1
SIM_NAME=$2

show_help() {
  print_message "${_USAGE} : check_sim <user_name> <sim_name>"
  exit;
}

# begin of logic
if [ $# -lt 2 ];then
  show_help
  exit;
fi

# check if the user exists
if user_exists ${USER_NAME} > /dev/null; then
  print_message "${_THE_USER} ${USER_NAME} ${_EXISTS}." "ok"
else
  print_message "${_THE_USER} ${USER_NAME} ${_DOES_NOT_EXIST}." "notok"
  exit 1;
fi

# check if the simulator folder exists
if simulator_folder_exists ${USER_NAME} ${SIM_NAME} > /dev/null;then
  print_message "${_THE_FOLDER} ${SIM_FOLDER} ${_EXISTS}." "ok"
else
  print_message "${_THE_FOLDER} ${SIM_FOLDER} ${_DOES_NOT_EXIST}." "notok"
  exit 1;
fi

# check the simulator pid
PID=$(get_sim_pid ${USER_NAME} ${SIM_NAME})
if [ $? = 0 ]; then
  print_message "${_THE_PID_FILE} ${_EXISTS}." "ok"
  if check_pid ${PID} > /dev/null;then
    print_message "${_PID_IS_RUNNING}." "ok"
  else
    print_message "${_PID_IS_NOT_RUNNING}." "notok"
  fi
else
  print_message "${_THE_PID_FILE} ${_DOES_NOT_EXIST}." "notok"
  exit 1;
fi

# check if the tmux session is running
if tmux_session_exists "os-${USER_NAME}"; then
  print_message "${_THE_TMUX_SESSION} ${_IS_RUNNING}." "ok"
else
  print_message "${_THE_TMUX_SESSION} ${_IS_NOT_RUNNING}." "notok"
fi

# check if the tmux window is running
if tmux_window_exists "os-${USER_NAME}" "${SIM_NAME}"; then
  print_message "${_THE_TMUX_WINDOW} ${_IS_RUNNING}." "ok"
else
  print_message "${_THE_TMUX_WINDOW} ${_IS_NOT_RUNNING}." "notok"
  exit 1;
fi

# check if the console is answering
if simulator_console_is_answering "${USER_NAME}" "${SIM_NAME}"; then
  print_message "${_THE_SIMULATOR_CONSOLE} ${_IS_ANSWERING}." "ok"
else
  print_message "${_THE_SIMULATOR_CONSOLE} ${_IS_NOT_ANSWERING}." "notok"
  exit 1;
fi
