#! /bin/bash

if [ $# -lt 2 ];then
  echo $"Usage : check_sim <user_name> <sim_name>"
  exit;
fi

# ======================
#         config
# ======================
# check if the config file exists
if [ ! -f "/etc/ostmu/ostmu.conf" ]; then
  echo $"/etc/ostmu/ostmu.conf file not found."
  exit 1;
fi

# include the config
source "/etc/ostmu/ostmu.conf"

# lang
TEXTDOMAIN=ostmu
TEXTDOMAINDIR="${OSTMU_FOLDER}/locale"

# user
USER_HOME=$(eval echo ~${SUDO_USER})
#user_config_folder_path="${USER_HOME}"/"${USER_CONFIG_FOLDER_NAME}"

# include the colors declarations
source "${OSTMU_FOLDER}/includes/theme"

# include functions files
source "${OSTMU_FOLDER}/includes/sys"
source "${OSTMU_FOLDER}/includes/users"
source "${OSTMU_FOLDER}/includes/tmux"
source "${OSTMU_FOLDER}/includes/sims"

# define some vars
user_name=$1
sim_name=$2
success=0

# ======================
#         checks
# ======================

# check if the user exists
if user_exists ${user_name} > /dev/null; then
  echo -e ${SymbolOk} $"The user ${user_name} exists."
else
  echo -e ${SymbolNotOk} $"The user ${user_name} does not exist."
  exit 1;
fi

# check if the simulator folder exists
if simulator_folder_exists ${user_name} ${sim_name} > /dev/null;then
  echo -e ${SymbolOk} $"The folder ${sim_folder} exists."
else
  echo -e ${SymbolNotOk} $"The folder ${sim_folder} does not exist."
  exit 1;
fi

# load the simulator .ostmu config file
config_file="/home/${user_name}/.opensimulator/${sim_name}.sim/.ostmu"
if [ ! -f ${config_file} ]; then
  echo -e ${SymbolNotOk} $"The file ${config_file} does not exist."
  exit 1;
fi
source ${config_file}

# check the simulator pid
PID=$(get_sim_pid ${user_name} ${sim_name})
if [ $? = 0 ]; then
  echo -e ${SymbolOk} $"The PID file exists."
  if check_pid ${PID} > /dev/null;then
    echo -e ${SymbolOk} $"PID is running."
  else
    echo -e ${SymbolNotOk} $"PID is not running."
    exit 1;
  fi
else
  echo -e ${SymbolNotOk} $"The file PID does not exist."
  exit 1;
fi

# check if the tmux session is running
if tmux_session_exists "${user_name}" "${sim_name}"; then
  echo -e ${SymbolOk} $"The tmux session is running."
else
  echo -e ${SymbolNotOk} $"The tmux session is not running."
  exit 1;
fi

# check if the tmux window is running
if tmux_window_exists "${user_name}" "${sim_name}"; then
  echo -e ${SymbolOk} $"The tmux window is running."
else
  echo -e ${SymbolNotOk} $"The tmux window is not running."
  exit 1;
fi

# check if the console is answering
#if simulator_console_is_answering "${user_name}" "${sim_name}"; then
#  echo -e ${SymbolOk} $"The simulator console is answering."
#else
#  echo -e ${SymbolNotOk} $"The simulator console is not answering."
#  exit 1;
#fi

# get the user db password
# @todo : see sqlite
db_pass_file="/home/${1}/.opensimulator/db_pass"
if [ -f ${db_pass_file} ]; then
  db_password=`cat ${db_pass_file}`
else
  echo -e ${SymbolNotOk} $"The file ${db_pass_file} does not exist."
  exit 1;
fi

# check if the regions are responding
regions=$(get_simulator_regions ${user_name} ${db_password} ${sim_name})
for region in $regions; do
  region_stats_is_answering "http://${EXTERNAL_HOST_NAME}" ${SIM_PORT} $region
  if [ $? = 0 ]; then
    echo -e ${SymbolOk} $"The region ${region} is answering."
  else
    echo -e ${SymbolNotOk} $"The region ${region} is not answering."
    exit 1;
  fi
done


