#! /bin/bash

# include some files
OPENSIM_SCRIPT_FOLDER="/opt/opensim/scripts"
source "${OPENSIM_SCRIPT_FOLDER}/etc/config"

# define some vars
USER_NAME=$1
SIM_NAME=$2

show_help() {
  echo "Usage : check_sim <user_name> <sim_name>"
  exit;
}

# begin of logic
if [ $# -lt 2 ];then
  show_help
  exit;
fi

# check if the user exists
if user_exists ${USER_NAME} > /dev/null; then
  echo -e "${SymbolOk}User ${USER_NAME} exists."
else
  echo -e "${SymbolNotOk}User ${USER_NAME} does not exist."
  exit 1;
fi

# check if the simulator folder exists
if simulator_folder_exists ${USER_NAME} ${SIM_NAME} > /dev/null;then
  echo -e "${SymbolOk}Folder ${SIM_FOLDER} exists."
else
  echo -e "${SymbolNotOk}Folder ${SIM_FOLDER} does not exist."
  exit 1;
fi

# check the simulator pid
PID=$(get_sim_pid ${USER_NAME} ${SIM_NAME})
if [ $? = 0 ]; then
  echo -e "${SymbolOk}Pid file exists."
  if check_pid ${PID} > /dev/null;then
    echo -e "${SymbolOk}Pid is running."
  else
    echo -e "${SymbolNotOk}Pid is not running."
  fi
else
  echo -e "${SymbolNotOk}Pid file does not exist."
  exit 1;
fi

# check if the tmux session is running
if tmux_session_exists "os-${USER_NAME}"; then
  echo -e "${SymbolOk}Tmux session is running."
else
  echo -e "${SymbolNotOk}Tmux session is not running."
fi

# check if the tmux window is running
if tmux_window_exists "os-${USER_NAME}" "${SIM_NAME}"; then
  echo -e "${SymbolOk}Tmux window is running."
else
  echo -e "${SymbolNotOk}Tmux window is not running."
  exit 1;
fi

# check if the console is answering
if simulator_console_is_answering "${USER_NAME}" "${SIM_NAME}"; then
  echo -e "${SymbolOk}The simulator console is answering."
else
  echo -e "${SymbolNotOk}The simulator console is not answering."
  exit 1;
fi
