#! /bin/bash

# check if root
if [[ $EUID -ne 0 ]]; then
   echo $"This script must be run as root" 1>&2
   exit 1
fi

# include the config
OSTMU_FOLDER="/opt/ostmu"
source "${OSTMU_FOLDER}/etc/config"

# define some vars
USER_NAME=$1
SIM_NAME=$2
USER_PORT="0"
SIM_PORT="0"
DB_PASSWORD=`date | md5sum | cut -c1-8`

show_help() {
  echo $"Usage : create_sim <user_name> <sim_name>"
  exit;
}

add_file() {
  cat "${OSTMU_INI_MODELS_FOLDER}/$1" | \
  sed -e 's/<\[user_name\]>/'${USER_NAME}'/g' \
  -e 's/<\[grid_ip\]>/'${OPENSIM_GRID_IP}'/g' \
  -e 's/<\[db_password\]>/'${DB_PASSWORD}'/g' \
  -e 's/<\[sim_name\]>/'${SIM_NAME}'/g' \
  -e 's/<\[sim_port\]>/'${SIM_PORT}'/g' > $2
}

get_next_available_user_port() {
  # remove empty lines in file
  sed -i '/^$/d' "${OSTMU_PORTS_FILE}"
  # count lines
  users_qty=$(wc -l < "${OSTMU_PORTS_FILE}")
  next_user_nbr=$((${users_qty} + 1))
  if [ ${next_user_nbr} -lt 10 ];then
    USER_PORT="10${next_user_nbr}00"
  else
    if [ ${next_user_nbr} -gt 99 ];then
      USER_PORT=$((${next_user_nbr} + 100))"00"
    else
      USER_PORT="1${next_user_nbr}00"
    fi
  fi
  echo "${USER_NAME};${USER_PORT}" >> "${OSTMU_PORTS_FILE}"
}

create_sim_files() {
  # count user sim folders
  sim_files_qty=$(find ${USER_CONFIG_FOLDER_PATH} -type d -name "*.sim" | wc -l)
  if [ ${sim_files_qty} -gt 9 ];then
    print_message "${_MAX_10_SIMS_PER_USER}" "error"
    exit;
  fi
  # get the user port
  user_port_line=$(grep "^${USER_NAME}" "${OSTMU_PORTS_FILE}")
  if [ "${user_port_line}" ];then
    # get the user port
    USER_PORT=$(echo "${user_port_line}" | cut -d ";" -f2)
  else
    get_next_available_user_port
  fi
  # define sim port
  if [ ${sim_files_qty} = 0 ];then
    SIM_PORT=${USER_PORT}
  else
    SIM_PORT=$((${USER_PORT} + $((${sim_files_qty} * 10))))
  fi
  # add root files
  mkdir -p "$1"
  add_file "OpenSim.exe.config" "$1/OpenSim.exe.config"
  add_file "OpenSim.ini" "$1/OpenSim.ini"
  # config-include
  mkdir -p "$1/config-include"
  add_file "GridCommon.ini" "$1/config-include/GridCommon.ini"
  add_file "GridHypergrid.ini" "$1/config-include/GridHypergrid.ini"
  # log
  mkdir -p "$1/log"
  # temp
  mkdir -p "$1/temp"
  # regions
  mkdir -p "$1/regions"
  add_file "Regions.ini" "$1/regions/Regions.ini"
  # change ownership
  chown -R "${USER_NAME}":"${USER_NAME}" "$1"
}

# begin of logic
if [ $# -lt 2 ];then
  show_help
  exit;
fi

# check if the user exists
if user_exists ${USER_NAME} > /dev/null; then
  echo -e ${SymbolOk} $"The user ${USER_NAME} exists."
else
  echo -e ${SymbolNotOk} $"The user ${USER_NAME} does not exist."
  exit 1;
fi

# check for the config folder
if [ ! -d "/var/lib/ostmu" ]; then
  mkdir -p "/var/lib/ostmu"
  if [ ! $? -eq 0 ]; then
    exit 1;
  else
    echo -e ${SymbolOk} $"The folder /var/lib/ostmu was created."
  fi
else
  echo -e ${SymbolOk} $"The folder /var/lib/ostmu exists."
fi

# check if the port file exists and if not, create it
if [ ! -f ${OSTMU_PORTS_FILE} ]; then
  touch "${OSTMU_PORTS_FILE}"
  if [ ! $? -eq 0 ]; then
    exit 1;
  else
    echo -e ${SymbolOk} $"The file ${OSTMU_PORTS_FILE} was created."
  fi
else
  echo -e ${SymbolOk} $"The file ${OSTMU_PORTS_FILE} exists."
fi

# check if the ports file is writable
if [ ! -w ${OSTMU_PORTS_FILE} ]; then
  echo -e ${SymbolOk} $"The ports file is not writable"
  exit 1;
fi

# check if the user config folder exists and if not, create it.
if [ ! -d "${USER_CONFIG_FOLDER_PATH}" ];then
  mkdir -p "${USER_CONFIG_FOLDER_PATH}"
  if [ ! $? -eq 0 ]; then
    exit 1;
  else
    echo -e ${SymbolOk} $"The folder ${USER_CONFIG_FOLDER_PATH} was created."
  fi
  chown "${USER_NAME}":"${USER_NAME}" "${USER_CONFIG_FOLDER_PATH}"
  if [ ! $? -eq 0 ]; then
    exit 1;
  else
    echo -e ${SymbolOk} $"The ownership of the folder ${USER_CONFIG_FOLDER_PATH} was set to ${USER_NAME}":"${USER_NAME}."
  fi
else
  echo -e ${SymbolOk} $"The folder ${USER_CONFIG_FOLDER_PATH} exists."
fi

if [ ${USE_MYSQL} == 1 ]; then
  # check if the db password file exit and if not, create it
  if [ -f "${USER_CONFIG_FOLDER_PATH}/db_pass" ];then
    DB_PASSWORD=`cat ${USER_CONFIG_FOLDER_PATH}/db_pass`
  else
    echo ${DB_PASSWORD} > "${USER_CONFIG_FOLDER_PATH}/db_pass"
    if [ ! $? -eq 0 ]; then
      exit 1;
    else
      echo -e ${SymbolOk} $"The file ${USER_CONFIG_FOLDER_PATH}/db_pass was created."
    fi
    chown "${USER_NAME}":"${USER_NAME}" "${USER_CONFIG_FOLDER_PATH}/db_pass"
    if [ ! $? -eq 0 ]; then
      exit 1;
    else
      echo -e ${SymbolOk} $"The ownership of the file ${USER_CONFIG_FOLDER_PATH}/db_pass was set to ${USER_NAME}":"${USER_NAME}."
    fi
  fi

  # load the mysql functions file
  source "${OSTMU_FOLDER}/includes/mysql"

  # check if the user exists in the database
  mysql_check_if_user_exists ${USER_NAME};
  if [ $? -eq 0 ]; then
    mysql_create_user ${USER_NAME} ${DB_PASSWORD}
    echo -e ${SymbolOk} $"The user ${USER_NAME} was created in the database."
  else
    echo -e ${SymbolOk} $"The user ${USER_NAME} exists in the database."
  fi

  # create the database
  mysql_create_database ${USER_NAME} "sim_${USER_NAME}_${SIM_NAME}"
fi

# check if the simulator folder exists and if not, create it
SIM_FOLDER="${USER_CONFIG_FOLDER_PATH}/${SIM_NAME}.sim"
if [ ! -d "${SIM_FOLDER}" ];then
  create_sim_files "${SIM_FOLDER}"
  echo -e ${SymbolOk} $"The folder ${SIM_FOLDER} was created."
else
  echo -e ${SymbolOk} $"The folder ${SIM_FOLDER} exists."
fi
