#! /bin/bash

# define some vars
OSTMU_FOLDER="/opt/ostmu"
source "${OSTMU_FOLDER}/etc/config"


# check if the opensim bin files exist
if [ ! -d "${OPENSIM_FOLDER}" ];then
  print_message "${_THE_OPENSIM_BIN_FOLDER_DOES_NOT_EXIST}" "error"
  exit 1;
else
  print_message "${_THE_OPENSIM_BIN_FOLDER_EXISTS}" "ok"
fi

# check if the socket folder exist
if [ ! -d "${TMUX_SOCKET_FOLDER}" ]; then
  mkdir -p "${TMUX_SOCKET_FOLDER}"
  if [ ! $? -eq 0 ]; then
    exit 1;
  else
    print_message "${_THE_FOLDER} ${TMUX_SOCKET_FOLDER} ${_EXISTS}." "ok"
  fi
else
  print_message "${_THE_FOLDER} ${TMUX_SOCKET_FOLDER} ${_EXISTS}." "ok"
fi

# check ig the socket folder has the good group ownership
if [ $(stat -c %G "${TMUX_SOCKET_FOLDER}") != "${TMUX_SOCKET_FOLDER_GROUP_NAME}" ]; then
  chown root:"${TMUX_SOCKET_FOLDER_GROUP_NAME}" "${TMUX_SOCKET_FOLDER}"
  if [ ! $? -eq 0 ]; then
    exit 1;
  else
    print_message "${_THE_FOLDER} ${TMUX_SOCKET_FOLDER} ${_HAVE_GOOD_GROUP_OWNERSHIP}." "ok"
  fi
else
  print_message "${_THE_FOLDER} ${TMUX_SOCKET_FOLDER} ${_HAVE_GOOD_GROUP_OWNERSHIP}." "ok"
fi

# check if the socket folder is writable to everyone
if [ ! $(stat -c %a "${TMUX_SOCKET_FOLDER}") = "2770" ]; then
  chmod 2770 "${TMUX_SOCKET_FOLDER}"
  if [ ! $? -eq 0 ]; then
    exit 1;
  else
    print_message "${_THE_PERMISSIONS_OF} ${TMUX_SOCKET_FOLDER} ${_ARE} 2770" "ok"
  fi
else
  print_message "${_THE_PERMISSIONS_OF} ${TMUX_SOCKET_FOLDER} ${_ARE} 2770" "ok"
fi
