#! /bin/bash

# include the config
OPENSIM_SCRIPT_FOLDER="/opt/opensim/scripts"
source "${OPENSIM_SCRIPT_FOLDER}/etc/config"

# define some vars
declare -a SIM_NAMES=()
declare -a WINDOW=()
declare -a NO_WINDOW=()

echo "${ColReset}=================="
echo "Starting..."
echo "=================="

# check if the config folder exists
if [ ! -d "$OPENSIM_LOCAL_CONFIG_FOLDER" ]; then
	echo -e "${ColRedF}${LOG_CONFIG}Directory ${OPENSIM_LOCAL_CONFIG_FOLDER} does not exist${ColReset}"
	exit 1;
fi

# get the .sim folders in config
cd "${OPENSIM_LOCAL_CONFIG_FOLDER}"
for i in *.sim;do
	if [ -d $i ]; then
		fullname=$(basename "$i")
		#~ extension="${fullname##*.}"
		shortname="${fullname%.*}"
    echo -e "${ColGreenF}${LOG_CONFIG}${fullname} found.${ColReset}"
		SIM_NAMES=("${SIM_NAMES[@]}" "${shortname}")
	fi
done

# check if there are ini files
sim_folders_qty=${#SIM_NAMES[@]}
if [ ${sim_folders_qty} -eq 0 ]; then
	echo -e "${ColRedF}${LOG_CONFIG}There are no .sim folder in ${OPENSIM_LOCAL_CONFIG_FOLDER}.${ColReset}"
  echo "Exiting"
	exit 1;
fi

echo -e "${LOG_CONFIG}There are $sim_folders_qty .sim folders in your opensim config folder."

# check if there is a session for the user
session_name=os-${USER}
if tmux_session_exists ${session_name}; then
	echo -e "${ColGreenF}${LOG_TMUX_SESSION}Your OpenSim user session : "${session_name}" is running.${ColReset}"
else
	echo -e "${ColRedF}${LOG_TMUX_SESSION}Your OpenSim user session is not running.${ColReset}"
  echo -e "${ColYellowF}Do you wan to create your OpenSim user session ?${ColReset}"
	read -p "Enter y or n :"
	if [ "$REPLY" == "y" ]; then
    echo "${LOG_TMUX_SESSION}Creating user session."
		tmux -S "${TMUX_SOCKET_FOLDER}/${session_name}" new-session -s "${session_name}" -d
	else
		echo "Nothing else to do, exiting."
		exit 0;
	fi
fi

for simname in "${SIM_NAMES[@]}"; do
  if tmux_window_exists ${session_name} ${simname}; then
    echo -e "${ColGreenF}${LOG_TMUX_WINDOW}The $simname window exists.${ColReset}"
    WINDOW=("${WINDOW[@]}" "${simname}");
  else
    echo -e "${ColRedF}${LOG_TMUX_WINDOW}The $simname window does not exist.${ColReset}"
    NO_WINDOW=("${NO_WINDOW[@]}" "${simname}");
  fi
done

echo "${LOG_TMUX_WINDOW}There are ${#WINDOW[@]} running simulators."
echo "${LOG_TMUX_WINDOW}There are ${#NO_WINDOW[@]} non running simulators."

if [ ! "${#NO_WINDOW[@]}" -eq 0 ]; then
  echo -e "${ColBlinkOn}${ColYellowF}Do you want to start a new simulator ?${ColReset}${ColBlinkOff}"
  echo -e "Enter y or n :"
  read start_sim
  if [ "$start_sim" == "y" ]; then
    echo "Here are the available simulators :"
    i=0
    for simname in "${NO_WINDOW[@]}"; do
      i=$((i+1))
      echo "$i/ ${simname}"
    done
    echo -e "${ColBlinkOn}${ColYellowF}What simulator do you want to start ?${ColReset}${ColBlinkOff}"
    echo -e "Enter a number :"
    read answer
    if ! [[ "$answer" =~ ^[0-9]+$ ]] ; then
      echo -e "${ColRedF}Wrong answer${ColReset}"
      exit 0;
    fi
    if [ "$answer" -eq 0 ]; then
      exit 0;
    fi
    if [[ "${NO_WINDOW[($answer - 1)]}" ]]; then
      simname="${NO_WINDOW[($answer - 1)]}"
      echo "Creating the window called : ${simname}"
      tmux -S "${TMUX_SOCKET_FOLDER}/${session_name}" new-window -t "${session_name}" -n "${simname}"
      echo "Running the simulator"
      run_simulator "${USER}" "${simname}"
    else
      echo "There is no choice : $answer"
    fi
  fi
fi

echo -e "${ColYellowF}Do you want to see the session ?${ColReset}"
echo -e "Answer y or n :"
read attach_session

if [ "$attach_session" == "y" ]; then
  tmux -S "${TMUX_SOCKET_FOLDER}/${session_name}" attach -t "${session_name}"
fi
