#! /bin/bash

# include the config
OSTMU_FOLDER="/opt/ostmu"
source "${OSTMU_FOLDER}/etc/config"

# define some vars
declare -a SIM_NAMES=()
declare -a WINDOW=()
declare -a NO_WINDOW=()

# check if the config folder exists
if [ ! -d "$USER_CONFIG_FOLDER_PATH" ]; then
  echo -e ${SymbolNotOk} $"The folder ${USER_CONFIG_FOLDER_PATH} does not exist."
  exit 1;
fi

# get the .sim folders in config
cd "${USER_CONFIG_FOLDER_PATH}"
for i in *.sim;do
  if [ -d $i ]; then
    fullname=$(basename "$i")
    #~ extension="${fullname##*.}"
    shortname="${fullname%.*}"
    echo -e ${SymbolOk} $"The file ${fullname} exists."
    SIM_NAMES=("${SIM_NAMES[@]}" "${shortname}")
  fi
done

# check if there are ini files
sim_folders_qty=${#SIM_NAMES[@]}
if [ ${sim_folders_qty} -eq 0 ]; then
  echo -e ${SymbolNotOk} $"There are no .sim folders inside ${USER_CONFIG_FOLDER_PATH}."
  exit 1;
fi

# check if there is a session for the user
session_name=os-${USER}
if tmux_session_exists ${session_name}; then
  echo -e ${SymbolOk} $"Your user session : "${session_name}" is running."
else
  echo -e ${SymbolNotOk} $"Your user session is not running."
  echo -e ${ColYellowF} $"Do you want to create your user session ?" ${ColReset}
  read -p $"Enter y or n :"
  if [ "$REPLY" == "y" ]; then
    echo $"Creating your user session."
    tmux -S "${TMUX_SOCKET_FOLDER}/${session_name}" new-session -s "${session_name}" -d
  else
    exit 0;
  fi
fi

for simname in "${SIM_NAMES[@]}"; do
  if tmux_window_exists ${session_name} ${simname}; then
    echo -e ${SymbolOk} $"The tmux window ${simname} exists."
    WINDOW=("${WINDOW[@]}" "${simname}");
  else
    echo -e ${SymbolNotOk} $"The tmux window ${simname} does not exist."
    NO_WINDOW=("${NO_WINDOW[@]}" "${simname}");
  fi
done

echo $"${#WINDOW[@]} running simulators."
echo $"${#NO_WINDOW[@]} non running simulators."

if [ ! "${#NO_WINDOW[@]}" -eq 0 ]; then
  echo -e ${ColYellowF} $"Do you want to start a new simulator ?" ${ColReset}
  echo $"Enter y or n :"
  read start_sim
  if [ "$start_sim" == "y" ]; then
    echo $"available simulators :"
    i=0
    for simname in "${NO_WINDOW[@]}"; do
      i=$((i+1))
      echo "$i/ ${simname}"
    done
    echo -e ${ColYellowF} $"What simulator do you want to start ?" ${ColReset}
    echo $"Enter a number :"
    read answer
    if ! [[ "$answer" =~ ^[0-9]+$ ]] ; then
      echo -e ${SymbolNotOk} $"Wrong answer. Good bye."
      exit 1;
    fi
    if [ "$answer" -eq 0 ]; then
      exit 0;
    fi
    if [[ "${NO_WINDOW[($answer - 1)]}" ]]; then
      simname="${NO_WINDOW[($answer - 1)]}"
      echo $"Creating the window : ${simname}"
      tmux -S "${TMUX_SOCKET_FOLDER}/${session_name}" new-window -t "${session_name}" -n "${simname}"
      echo $"Starting the simulator"
      run_simulator "${USER}" "${simname}"
    else
      echo -e ${SymbolNotOk} $"Wrong answer. Good bye."
      exit 1;
    fi
  fi
fi

echo -e ${ColYellowF} "Do you want to see the session ?" ${ColReset}
echo $"Enter y or n :"
read attach_session

if [ "$attach_session" == "y" ]; then
  tmux -S "${TMUX_SOCKET_FOLDER}/${session_name}" attach -t "${session_name}"
fi
