#! /bin/bash

# check if root
if [[ $EUID -ne 0 ]]; then
   echo $"This script must be run as root" 1>&2
   exit 1
fi

# include the config
OSTMU_FOLDER="/opt/ostmu"
source "${OSTMU_FOLDER}/etc/config"
source "${OSTMU_FOLDER}/includes/mysql"

user_name=$1
user_config_folder_path="/home/${user_name}/${USER_CONFIG_FOLDER_NAME}"

show_help() {
  echo $"Usage : update_password <user_name>"
  exit;
}

# begin of logic
if [ $# -lt 1 ];then
  show_help
  exit;
fi

# check if the user password file exists
if [ -f "${user_config_folder_path}/db_pass" ];then
  echo -e ${SymbolOk} $"The user password file exists."
  db_password=`cat ${user_config_folder_path}/db_pass`
  mysql_update_password "${user_name}" "${db_password}"
else
  echo -e ${SymbolNotOk} $"The user password file does not exist."
  exit 1;
fi
