#! /bin/bash

# check if root
if [[ $EUID -ne 0 ]]; then
   echo $"This script must be run as root" 1>&2
   exit 1
fi

if [ $# -lt 1 ];then
  echo $"Usage : update_password <user_name>"
  exit;
fi

# include the config
source "/etc/ostmu/ostmu.conf"

# lang
TEXTDOMAIN=ostmu
TEXTDOMAINDIR="${OSTMU_FOLDER}/locale"

# user
USER_HOME=$(eval echo ~${SUDO_USER})
#user_config_folder_path="${USER_HOME}"/"${USER_CONFIG_FOLDER_NAME}"

# include the colors declarations
source "${OSTMU_FOLDER}/includes/theme"

# include functions files
source "${OSTMU_FOLDER}/includes/mysql"

user_name=$1
user_config_folder_path="/home/${user_name}/${USER_CONFIG_FOLDER_NAME}"

# check if the user password file exists
if [ -f "${user_config_folder_path}/db_pass" ];then
  echo -e ${SymbolOk} $"The user password file exists."
  db_password=`cat ${user_config_folder_path}/db_pass`
  mysql_update_password "${user_name}" "${db_password}"
else
  echo -e ${SymbolNotOk} $"The user password file does not exist."
  exit 1;
fi
