#! /bin/bash

# opensim path
OPENSIM_FOLDER="/opt/opensim/bin"
OPENSIM_BIN="${OPENSIM_FOLDER}/OpenSim.exe"

# tmux
TMUX_SOCKET_FOLDER="/tmp/tmux/sockets/opensim"
TMUX_SOCKET_FOLDER_GROUP_NAME="tmux-share"

# lang
source "${OSTMU_FOLDER}/includes/lang/eng"

# ostmu
OSTMU_INI_MODELS_FOLDER="/opt/opensim/scripts/models"
OSTMU_PORTS_FILE="${OSTMU_FOLDER}/etc/ports"
USER_CONFIG_FILE_NAME=".opensim"

# NOTHING SHOULD BE CHANGED UNDER THIS LINE
USER_HOME=$(eval echo ~${SUDO_USER})
OPENSIM_LOCAL_CONFIG_FOLDER="${USER_HOME}"/"${USER_CONFIG_FILE_NAME}"

# include the colors declarations
source "${OSTMU_FOLDER}/includes/theme"

# include functions files
source "${OSTMU_FOLDER}/includes/sys"
source "${OSTMU_FOLDER}/includes/users"
source "${OSTMU_FOLDER}/includes/tmux"
source "${OSTMU_FOLDER}/includes/sims"
