#! /bin/bash

MYSQL=`which mysql`

# $1: username
mysql_check_if_user_exists() {
  exists=`$MYSQL --batch --skip-column-names -u ${MYSQL_ROOT_USERNAME} -p${MYSQL_ROOT_PASSWORD} -e "SELECT EXISTS(SELECT 1 FROM mysql.user WHERE User = '$1');"`
  if [ $exists == "1" ]; then
    return 1;
  else
    return 0;
  fi
}

# $1: username
# $2: password
mysql_create_user() {
  echo "flush privileges;CREATE USER '$1'@'localhost' IDENTIFIED BY '$2';GRANT USAGE ON *.* TO '$1'@'localhost' IDENTIFIED BY '$2' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;" | $MYSQL --batch -u ${MYSQL_ROOT_USERNAME} -p${MYSQL_ROOT_PASSWORD}
}

# $1: username
# $2: database
mysql_create_database() {
  echo "CREATE DATABASE IF NOT EXISTS $2;GRANT ALL PRIVILEGES ON $2.* TO '$1'@'localhost';" | $MYSQL --batch --skip-column-names -u ${MYSQL_ROOT_USERNAME} -p${MYSQL_ROOT_PASSWORD}
}
