#! /bin/bash

# Check if the tmux session exists
# $1 user name
# $2 session name
tmux_session_exists() {
  tmux -S "${TMUX_SOCKET_FOLDER}/${1}/${2}" list-session 2>&1 | grep -q "^${2}"
}

# Check if the tmux window exists
# $1 user name
# $2 session name
# $3 Window name
tmux_window_exists() {
  tmux -S "${TMUX_SOCKET_FOLDER}/${1}/${2}" list-window -t "${2}" 2>&1 | grep -q ": $3 \["
}
