#! /bin/bash

declare -a has_window=()
declare -a has_no_window=()

# check if there is a session for the user
session_name="os-${USER}"
if tmux_session_exists ${USER} ${session_name}; then
  echo -e ${SymbolOk} $"Your user session : ${session_name} is running."
else
  echo -e ${SymbolNotOk} $"Your user session is not running."
  echo -e ${ColYellowF} $"Do you want to create your user session ?" ${ColReset}
  read -p $"Enter y or n :"
  if [ "$REPLY" == "y" ]; then
    echo $"Creating your user session."
    tmux -S "${TMUX_SOCKET_FOLDER}/${USER}/${session_name}" new-session -s "${session_name}" -d
  else
    exit 0;
  fi
fi

# get the list of running tmux windows
for simname in "${sim_names[@]}"; do
  if tmux_window_exists ${USER} ${session_name} ${simname}; then
    echo -e ${SymbolOk} $"The tmux window ${simname} exists."
    has_window=("${has_window[@]}" "${simname}");
  else
    echo -e ${SymbolNotOk} $"The tmux window ${simname} does not exist."
    has_no_window=("${has_no_window[@]}" "${simname}");
  fi
done

echo $"${#has_window[@]} running simulators."
echo $"${#has_no_window[@]} non running simulators."

if [ ! "${#has_no_window[@]}" -eq 0 ]; then
  echo -e ${ColYellowF} $"Do you want to start a new simulator ?" ${ColReset}
  echo $"Enter y or n :"
  read start_sim
  if [ "$start_sim" == "y" ]; then
    echo $"available simulators :"
    i=0
    for simname in "${has_no_window[@]}"; do
      i=$((i+1))
      echo "$i/ ${simname}"
    done
    echo -e ${ColYellowF} $"What simulator do you want to start ?" ${ColReset}
    echo $"Enter a number :"
    read sim_number
    if ! [[ "$sim_number" =~ ^[0-9]+$ ]] ; then
      echo -e ${SymbolNotOk} $"Wrong answer. Good bye."
      exit 1;
    fi
    if [ "$sim_number" -eq 0 ]; then
      echo -e ${SymbolNotOk} $"Wrong answer. Good bye."
      exit 0;
    fi
    if [[ "${has_no_window[($sim_number - 1)]}" ]]; then
      simname="${has_no_window[($sim_number - 1)]}"
      echo $"Creating the window : ${simname}"
      if [ ${#has_window[@]} -eq 0 ]; then
        tmux -S "${TMUX_SOCKET_FOLDER}/${USER}/${session_name}" rename-window -t "${session_name}":0 "${simname}"
      else
        tmux -S "${TMUX_SOCKET_FOLDER}/${USER}/${session_name}" new-window -t "${session_name}" -n "${simname}"
      fi
      echo $"Starting the simulator"
      run_simulator "${USER}" "${session_name}" "${simname}"
    else
      echo -e ${SymbolNotOk} $"Wrong answer. Good bye."
      exit 1;
    fi
  fi
fi

echo -e ${ColYellowF} $"Do you want to see the session ?" ${ColReset}
echo $"Enter y or n :"
read attach_session

if [ "$attach_session" == "y" ]; then
  tmux -S "${TMUX_SOCKET_FOLDER}/${USER}/${session_name}" attach -t "${session_name}"
fi
