#! /bin/bash

declare -a has_session=()
declare -a has_no_session=()

# get the list of running tmux sessions
for simname in "${sim_names[@]}"; do
  session_name="os-${USER}-${simname}"
  if tmux_session_exists ${USER} ${session_name}; then
    echo -e ${SymbolOk} $"The tmux session ${session_name} exists."
    has_session=("${has_session[@]}" "${simname}");
  else
    echo -e ${SymbolNotOk} $"The tmux session ${session_name} does not exist."
    has_no_session=("${has_no_session[@]}" "${simname}");
  fi
done

echo $"${#has_session[@]} running simulators."
echo $"${#has_no_session[@]} non running simulators."

if [ ! "${#has_no_session[@]}" -eq 0 ]; then
  echo -e ${ColYellowF} $"Do you want to start a new simulator ?" ${ColReset}
  echo $"Enter y or n :"
  read start_sim
  if [ "$start_sim" == "y" ]; then
    echo $"available simulators :"
    i=0
    for simname in "${has_no_session[@]}"; do
      i=$((i+1))
      echo "$i/ ${simname}"
    done
    echo -e ${ColYellowF} $"What simulator do you want to start ?" ${ColReset}
    echo $"Enter a number :"
    read sim_number
    if ! [[ "$sim_number" =~ ^[0-9]+$ ]] ; then
      echo -e ${SymbolNotOk} $"Wrong answer. Good bye."
      exit 1;
    fi
    if [ "$sim_number" -eq 0 ]; then
      echo -e ${SymbolNotOk} $"Wrong answer. Good bye."
      exit 0;
    fi
    if [[ "${has_no_session[($sim_number - 1)]}" ]]; then
      simname="${has_no_session[($sim_number - 1)]}"
      session_name="os-${USER}-${simname}"
      echo $"Creating the session : ${simname}"
      tmux -S "${TMUX_SOCKET_FOLDER}/${USER}/${session_name}" new-session -s "${session_name}" -d
      tmux -S "${TMUX_SOCKET_FOLDER}/${USER}/${session_name}" rename-window -t "${session_name}":0 "${simname}"
      echo $"Starting the simulator"
      run_simulator "${USER}" "${session_name}" "${simname}"
    else
      echo -e ${SymbolNotOk} $"Wrong answer. Good bye."
      exit 1;
    fi
  fi
fi


# get the available sessions
declare -a tmux_sessions=()
cd "${TMUX_SOCKET_FOLDER}/${USER}"
for i in *;do
  if [[ `tmux -S "${TMUX_SOCKET_FOLDER}/${USER}"/${i} list-session  2>&1 | cut -d":" -f1` = "$i" ]]; then
    tmux_sessions=("${tmux_sessions[@]}" "${i}")
  fi
done

if [ "${#tmux_sessions[@]}" -eq 0 ]; then
  exit;
fi

echo -e ${ColYellowF} $"Do you want to see a session ?" ${ColReset}
echo $"Enter y or n :"
read see_a_session
if [ "$see_a_session" == "n" ]; then
  exit 0;
fi

echo $"available sessions :"
i=0
for session_name in "${tmux_sessions[@]}"; do
  i=$((i+1))
  echo "$i/ ${session_name}"
done
echo -e ${ColYellowF} $"What session do you want to see ?" ${ColReset}
echo $"Enter a number :"
read session_number
if ! [[ "$session_number" =~ ^[0-9]+$ ]] ; then
  echo -e ${SymbolNotOk} $"Wrong answer. Good bye."
  exit 1;
fi
if [ "$session_number" -eq 0 ]; then
  echo -e ${SymbolNotOk} $"Wrong answer. Good bye."
  exit 0;
fi
if [[ "${tmux_sessions[($session_number - 1)]}" ]]; then
  tmux -S "${TMUX_SOCKET_FOLDER}/${USER}/${tmux_sessions[($session_number - 1)]}" attach -t "${tmux_sessions[($session_number - 1)]}"
else
  echo -e ${SymbolNotOk} $"Wrong answer. Good bye."
  exit 1;
fi
