#! /bin/bash

# check if the user exists
# $1 User name
user_exists() {
  if [ $(id -u ${1} 2>/dev/null) ]; then
    print_message "${_THE_USER} ${1} ${_EXISTS}." "ok"
    return 0;
  else
    print_message "${_THE_USER} ${1} ${_DOES_NOT_EXIST}." "notok"
    return 1;
  fi
}
