#! /bin/bash

# common
_EXISTS="exists"
_DOES_NOT_EXIST="does not exist"
_FOUND="found"
_NOT_FOUND="not found"
_USAGE="Usage"
_CREATING="Creating"
_CREATED="created"
_IS_RUNNING="is running"
_IS_NOT_RUNNING="is not running"
_IS_ANSWERING="is answering"
_IS_NOT_ANSWERING="is not answering"
_IS_NOT_WRITABLE="is not writable"
_ARE="are"
_ARE_NOT="are not"
_THERE_ARE="There are"
_ENTER_Y_OR_N="Enter y or n"
_ENTER_A_NUMBER="Enter a number"
_WRONG_ANSWER="Wrong answer"

# users
_THE_USER="The user"
_CREATING_THE_USER="Creating the user"

# sys
_THE_OSTMU_CONFIG_FOLDER_DOES_NOT_EXIST="The ostmu config folder does not exist"
_THE_PORTS_FILE_DOES_NOT_EXIST="The ports file does not exist"
_THE_PORTS_FILE_IS_NOT_WRITABLE="Le fichier de ports n'est pas accessible en écriture"
_FILE="file"
_THE_FILE="The file"
_CREATING_THE_FILE="Creating the file"
_FOLDER="folder"
_THE_FOLDER="The folder"
_CREATING_THE_FOLDER="Creating the folder"
_ERROR_CREATING_FOLDER="Error creating the folder"
_THE_PID_FILE="The pid file"
_PID_IS_RUNNING="Pid is running"
_PID_IS_NOT_RUNNING="Pid is not running"
_HAVE_GOOD_GROUP_OWNERSHIP="have the good group ownership"
_DOES_NOT_HAVE_GOOD_GROUP_OWNERSHIP="does not have the good group ownership"
_ASSIGNING_FOLDER_GROUP_TO="Assigning the folder group to"
_THE_PERMISSIONS_OF="The permissions of"

# sims
_THE_OPENSIM_BIN_FOLDER_DOES_NOT_EXIST="The opensim bin folder does not exist"
_MAX_10_SIMS_PER_USER="Maximum 10 sims per user"
_THE_SIMULATOR_CONSOLE="The simulator console"
_THERE_ARE_NO_SIM_FOLDERS_INSIDE="There are no sim folders inside"
_SIM_FOLDERS_INSIDE_YOUR_OPENSIM_FOLDER=".sim folders inside your opensim folder"
_RUNNING_SIMULATORS="running simulators"
_NON_RUNNING_SIMULATORS="non running simulators"
_DO_YOU_WANT_TO_START_A_NEW_SIMULATOR="Do you want to start a new simulator"
_WHAT_SIMULATOR_DO_YOU_WANT_TO_START="What simulator do you want to start"
_AVAILABLE_SIMULATORS="Available simulators"
_STARTING_THE_SIMULATOR="Starting the simulator"

# tmux
_THE_TMUX_SESSION="The tmux session"
_THE_TMUX_WINDOW="The tmux window"
_DO_YOU_WANT_TO_CREATE_YOUR_USER_SESSION="Do you wan to create your user session"
_YOUR_USER_SESSION="Your user session"
_CREATING_YOUR_USER_SESSION="Creating your user session"
_CREATING_THE_WINDOW="Creating the window"
_DO_YOU_WANT_TO_SEE_THE_SESSION="Do you want to see the session"

# mysql
_IN_THE_DATABASE="in the database"
